/**
 * List data — edit image and link per item anytime.
 *
 * Each entry:
 *   id        — stable identifier (optional, for your own tracking)
 *   title     — card heading
 *   subtitle  — short line under the title
 *   imageUrl  — src for the card image
 *   href      — URL opened when the card is clicked (use "#" for no navigation)
 */
window.LENSI_ITEMS = [
  {
    id: "01",
    title: "Aurora Frame",
    subtitle: "Northern light study",
    imageUrl: "https://picsum.photos/seed/lensi-01/800/600",
    href: "https://example.com/01",
  },
  {
    id: "02",
    title: "Coastal Haze",
    subtitle: "Morning shoreline",
    imageUrl: "https://picsum.photos/seed/lensi-02/800/600",
    href: "https://example.com/02",
  },
  {
    id: "03",
    title: "Urban Geometry",
    subtitle: "Lines and glass",
    imageUrl: "https://picsum.photos/seed/lensi-03/800/600",
    href: "https://example.com/03",
  },
  {
    id: "04",
    title: "Forest Path",
    subtitle: "Deep green corridor",
    imageUrl: "https://picsum.photos/seed/lensi-04/800/600",
    href: "https://example.com/04",
  },
  {
    id: "05",
    title: "Desert Bloom",
    subtitle: "Warm horizon",
    imageUrl: "https://picsum.photos/seed/lensi-05/800/600",
    href: "https://example.com/05",
  },
  {
    id: "06",
    title: "Studio Still",
    subtitle: "Controlled light",
    imageUrl: "https://picsum.photos/seed/lensi-06/800/600",
    href: "https://example.com/06",
  },
  {
    id: "07",
    title: "River Bend",
    subtitle: "Slow water",
    imageUrl: "https://picsum.photos/seed/lensi-07/800/600",
    href: "https://example.com/07",
  },
  {
    id: "08",
    title: "Night Market",
    subtitle: "Neon reflections",
    imageUrl: "https://picsum.photos/seed/lensi-08/800/600",
    href: "https://example.com/08",
  },
  {
    id: "09",
    title: "Mountain Lake",
    subtitle: "Mirror surface",
    imageUrl: "https://picsum.photos/seed/lensi-09/800/600",
    href: "https://example.com/09",
  },
  {
    id: "10",
    title: "Golden Hour",
    subtitle: "Late afternoon",
    imageUrl: "https://picsum.photos/seed/lensi-10/800/600",
    href: "https://example.com/10",
  },
  {
    id: "11",
    title: "Minimal Interior",
    subtitle: "Quiet room",
    imageUrl: "https://picsum.photos/seed/lensi-11/800/600",
    href: "https://example.com/11",
  },
  {
    id: "12",
    title: "Harbor Lights",
    subtitle: "Dock at dusk",
    imageUrl: "https://picsum.photos/seed/lensi-12/800/600",
    href: "https://example.com/12",
  },
  {
    id: "13",
    title: "Wildflower",
    subtitle: "Field detail",
    imageUrl: "https://picsum.photos/seed/lensi-13/800/600",
    href: "https://example.com/13",
  },
  {
    id: "14",
    title: "Snow Ridge",
    subtitle: "Alpine contrast",
    imageUrl: "https://picsum.photos/seed/lensi-14/800/600",
    href: "https://example.com/14",
  },
  {
    id: "15",
    title: "Café Corner",
    subtitle: "Street scene",
    imageUrl: "https://picsum.photos/seed/lensi-15/800/600",
    href: "https://example.com/15",
  },
  {
    id: "16",
    title: "Sand Patterns",
    subtitle: "Wind traces",
    imageUrl: "https://picsum.photos/seed/lensi-16/800/600",
    href: "https://example.com/16",
  },
  {
    id: "17",
    title: "Rain Window",
    subtitle: "Soft blur",
    imageUrl: "https://picsum.photos/seed/lensi-17/800/600",
    href: "https://example.com/17",
  },
  {
    id: "18",
    title: "Bridge Span",
    subtitle: "Steel and sky",
    imageUrl: "https://picsum.photos/seed/lensi-18/800/600",
    href: "https://example.com/18",
  },
  {
    id: "19",
    title: "Autumn Trail",
    subtitle: "Falling color",
    imageUrl: "https://picsum.photos/seed/lensi-19/800/600",
    href: "https://example.com/19",
  },
  {
    id: "20",
    title: "Open Road",
    subtitle: "Distance ahead",
    imageUrl: "https://picsum.photos/seed/lensi-20/800/600",
    href: "https://example.com/20",
  },
  {
    id: "21",
    title: "Ceramic Form",
    subtitle: "Shape study",
    imageUrl: "https://picsum.photos/seed/lensi-21/800/600",
    href: "https://example.com/21",
  },
  {
    id: "22",
    title: "Cloud Stack",
    subtitle: "Layered sky",
    imageUrl: "https://picsum.photos/seed/lensi-22/800/600",
    href: "https://example.com/22",
  },
  {
    id: "23",
    title: "Market Color",
    subtitle: "Fresh produce",
    imageUrl: "https://picsum.photos/seed/lensi-23/800/600",
    href: "https://example.com/23",
  },
  {
    id: "24",
    title: "Stone Steps",
    subtitle: "Old town",
    imageUrl: "https://picsum.photos/seed/lensi-24/800/600",
    href: "https://example.com/24",
  },
  {
    id: "25",
    title: "Pier View",
    subtitle: "Looking out",
    imageUrl: "https://picsum.photos/seed/lensi-25/800/600",
    href: "https://example.com/25",
  },
  {
    id: "26",
    title: "Bamboo Grove",
    subtitle: "Vertical rhythm",
    imageUrl: "https://picsum.photos/seed/lensi-26/800/600",
    href: "https://example.com/26",
  },
  {
    id: "27",
    title: "Workshop",
    subtitle: "Hands and tools",
    imageUrl: "https://picsum.photos/seed/lensi-27/800/600",
    href: "https://example.com/27",
  },
  {
    id: "28",
    title: "Twilight City",
    subtitle: "Blue hour",
    imageUrl: "https://picsum.photos/seed/lensi-28/800/600",
    href: "https://example.com/28",
  },
  {
    id: "29",
    title: "Meadow Light",
    subtitle: "Open field",
    imageUrl: "https://picsum.photos/seed/lensi-29/800/600",
    href: "https://example.com/29",
  },
  {
    id: "30",
    title: "Final Frame",
    subtitle: "Closing shot",
    imageUrl: "https://picsum.photos/seed/lensi-30/800/600",
    href: "https://example.com/30",
  },
];
